### PR TITLE
WIP: Changed the timestamp in Quick to use the timezone.

### PR DESCRIPTION
**Pull request by oyta**
Added timezone implementation to use the timezone of settings.TIME_ZONE

### CODE REVIEW

**Comment by joakim-hove** [comment]
If I had a $ for every time I have sworn about timezones I would be a rich man! I would prefer if you would use the (static) `TimeStamp` model from `sensors/models.py`. This should be enough:
```python
time_pp = TimeStamp.create( time )
```

**Comment by oyta** [comment]
I changed quick.py to only use the TimeStamp-implementation for all timestamps. I still got +00 hours in the view, but I am not sure what the TIME_ZONE is set to on the local server. How can I check that?

**Comment by oyta** [comment]
The
`time_pp = TimeStamp.create( time )`
is not using the desired format so I used
`time_pp = TimeStamp.parse_datetime(time).strftime('%b. %d, %H:%M') `

**Comment by joakim-hove** [comment]
>  How can I check that?

The time zone is initialized [here](https://github.com/FriskByBergen/friskby/blob/master/friskby/settings/__init__.py#L140) - i.e. you should check the environment variable `TZ` - which should be set to `Europe/Oslo`

**Comment by joakim-hove** [comment]
> time_pp = TimeStamp.parse_datetime(time).strftime('%b. %d, %H:%M')

Please add an optional `format`argument to the [`TimeStamp.create`](https://github.com/FriskByBergen/friskby/blob/master/sensor/models.py#L244) method instead:
```python
@classmethod
def create(cls , time = None, format = None):
     if format is None:
          format = cls.DATETIME_FORMAT
     if time is None:
          time = timezone.now()
     return time.strftime(format)
```
I am such a bastard ... ;-(

**Comment by joakim-hove** [comment]
Good effort - feel free to merge this when/if you are satisfied. We all **hate** timezones.

**Comment by oyta** [comment]
Hehe, no worries. Keep the corrections coming. I have used the TimeStamp now, my TZ is Europe/Oslo, but it still create strings with TZ equal to zulu time. I need to loo into it later.

**Comment by oyta** [comment]
It seems Django works with UTC and to get local time I specifically need to ask for it. Added it to the TimeZone.create as an option.

**Comment by mortalisk** [comment]
Could you explain to me the context? Are we using Europe/Oslo everywhere? Also in the DB? What behaviour changes with this PR?

**Comment by oyta** [comment]
DB = UTC. Currently the timestamps shown in Quick are in UTC. This PR
changes the timestamps in Quick to the timezone in the settings =
Europe/Oslo.
tir. 21. feb. 2017 kl. 10.42 skrev Morten Bendiksen <
notifications@github.com>:

**Comment by joakim-hove** [comment]
> DB = UTC. 

Correct.

> This PR changes the timestamps in Quick to the timezone in the settings =
Europe/Oslo.

Then we merge.

**Pull request merged**
