### PR TITLE
Removed raw sql

### PR DESCRIPTION
**Pull request by joakim-hove**
Some changes to the `quick`view:

1. Added simple get test.
2. Named url.
3. Removed raw sql - use Django orm.

Did not really understand the quick method, in particular it seems to fetch data for two weeks from the DB, but only one value is actually returned?

### CODE REVIEW

**Comment by joakim-hove** [comment]
@mortalisk - topp om du kan kommentere litt på denne. Jeg merger uansett en av dagene.

**Comment by mortalisk** [comment]
Hei Joakim. The code looks much better now. But I couldn't get it to work. It doesn't read the "time" query parameter anymore, and you have removed the code that used the last timestamp from the database. This was meant to make local testing easier until development is done, as it is cumbersome to dig the data out of the database manually and then pass it via the "time" parameter. I suggest we keep this functionality for now.

**Comment by joakim-hove** [comment]
ok - I will update.

16. jan. 2017 16:33 skrev "Morten Bendiksen" <notifications@github.com>:

Hei Joakim. The code looks much better now. But I couldn't get it to work.
It doesn't read the "time" query parameter anymore, and you have removed
the code that used the last timestamp from the database. This was meant to
make local testing easier until development is done, as it is cumbersome to
dig the data out of the database manually and then pass it via the "time"
parameter. I suggest we keep this functionality for now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FriskByBergen/friskby/pull/124#issuecomment-272892974>,
or mute the thread

**Comment by mortalisk** [comment]
Also, to answer the question about fetching two weeks of data: It is used in the template/html/javascript. The whole point of this view/template, is that everything needed by the page should already be part of the response. The browser shouldn't have to do extra round trips to the server.

**Comment by joakim-hove** [comment]
But the two weeks of data is never returned?

16. jan. 2017 17:06 skrev "Morten Bendiksen" <notifications@github.com>:

**Comment by mortalisk** [comment]
It is set in the context and used in the template to render html and
javascript


man. 16. jan. 2017 kl. 17.28 skrev Joakim Hove <notifications@github.com>:

**Comment by joakim-hove** [comment]
OK - this has been rebased; please try again.

**Comment by mortalisk** [comment]
Does the original version work on your machine? If it did, I suggest you should be able to get the same behaviour with your changes. If not, we need to figure out why it does not work on your machine. I get this error in the browser now:
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/quick/

Django Version: 1.10.3
Python Version: 2.7.12
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'rest_framework',
 'git_version',
 'api_key',
 'pythoncall',
 'time_series',
 'sensor',
 'plot',
 'filter')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')



Traceback:

File "/home/morten/src/friskby/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/home/morten/src/friskby/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/morten/src/friskby/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/morten/src/friskby/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/morten/src/friskby/venv/local/lib/python2.7/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/home/morten/src/friskby/venv/local/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/home/morten/src/friskby/friskby/views/quick.py" in get
  30.             pm10_type = MeasurementType.objects.get( name = "PM10" )

File "/home/morten/src/friskby/venv/local/lib/python2.7/site-packages/django/db/models/manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/home/morten/src/friskby/venv/local/lib/python2.7/site-packages/django/db/models/query.py" in get
  389.             (self.model._meta.object_name, num)

Exception Type: MultipleObjectsReturned at /quick/
Exception Value: get() returned more than one MeasurementType -- it returned 3!

```

**Comment by pgdr** [comment]
Jeg får også `MultipleObjectsReturned`.  Kanskje fra denne linjen:

> `pm10_type = MeasurementType.objects.get( name = "PM10" )`

**Comment by pgdr** [comment]
By the way, is there a way to dump the production database into my local postgres?

**Comment by joakim-hove** [comment]
> Does the original version work on your machine?

Dang - I just ran the tests ;-(

> pm10_type = MeasurementType.objects.get( name = "PM10" )

Yes - that is most probably the offending line; I must admit I thought about it when I wrote it. The name of measurument types have gradually been promoted from random data, i.e. the strings `"PM10"` and `"PM25"` to something resembling primary keys. That is obviously a weakness. I.

I suggest you got to http://localhost:8000/admin/sensor/measurementtype/ and make sure you have one-and-exactly-one element with name == "PM10" and "PM25".

**Comment by joakim-hove** [comment]
> By the way, is there a way to dump the production database into my local postgres?

The Heroku way: https://devcenter.heroku.com/articles/heroku-postgres-import-export

The database is a regular postgres database and you can use `pg_dump` with that. When you have the necessary Heroku credentials you can go to "Settings" in the Heroku GUI and find the connection string for the DB - nothing special about that.

**Pull request merged**
