### PR TITLE
Changed the function normalize of map.js

### PR DESCRIPTION
**Pull request by oyta**
I fixed the function according to what I think is the purpose of it. @mortalisk can you have a look? I may have misunderstood.. If so we can delete this PR.

### CODE REVIEW

**Comment by mortalisk** [comment]
The purpose of it was to change the test data a bit before visualizing I think, but I don't really remember. What does it do now?

**Comment by oyta** [comment]
Aha - the return value was used in the red and green settings of the RGB-color of the map icons. However, the function returned values outside the 0-255 legal value range of the RGB-color elements. The new function returns a value between minOut and maxOut based on where the value is between minIn and maxIn. 

E.g. Value = 5, minIn = 0, maxIn = 10, minOut = 0, maxOut = 100 ==> return 50. In other words it grades the color from green at 0 micro gram per m3 to red at 35 micro gram per m3.

**Comment by mortalisk** [comment]
Okay, yeah, this seems to be what I intended originally. But this is an improvement, so let|s merge it.

**Comment by pgdr** [comment]
Good, I deployed this together with the other PR just merged.

**Pull request merged**
