### PR TITLE
Only fetch one sensortype at a time.

### PR DESCRIPTION
**Pull request by mortalisk**
Use query parameters to navigate in time and sensors through links in page.

### CODE REVIEW

**Comment by pgdr** [comment]
You should rebase on top of master.

**Comment by pgdr** [comment]
But it looks very good and I'd like to see it merged as soon as possible!

If you rebase and push, I'll merge it immediately!

**Comment by mortalisk** [comment]
Rebased and maybe fixed conflicts. Didn't work though because of migration issues.

**Comment by joakim-hove** [comment]
Sorry about all these migration f... ups; please try another rebase.

**Comment by pgdr** [comment]
You might have to reset back some commits in this case!

As in
```bash
git checkout master
git reset --hard 2ef1365
git pull upstream master
git checkout quick_rest
git rebase master
```

**Comment by pgdr** [comment]
Good to hear.  I'll merge this pretty soon, I just want to make sure we get all the migrations-stuff corrected before we continue.

**Comment by pgdr** [comment]
Also, it seems to improve loading time:
```
        mean  +/- std,   ( p10  median p90 )  # times in seconds
before: 0.488 +/- 0.037, (0.450 0.480 0.540)  # raw db and algorithm as is today
after:  0.466 +/- 0.039, (0.430 0.450 0.530)  # db with delete test and reindex
morten: 0.369 +/- 0.029, (0.340 0.360 0.410)  # this branch
```

**Comment by pgdr** [comment]
Actually, I'll merge this now, but I'll leave it to Joakim to do the heroku-pushin.

**Pull request merged**
