### PR TITLE
created foreignkey from rawdata to sensor

### PR DESCRIPTION
**Pull request by pgdr**
The `RawData` is now _formally_ linked to `Sensor` in the sense that the `RawData` model (`rawdata` table) has a foreignkey to `Sensor`).

Needs migration.

Warning: The migration takes quite a while to run!

### CODE REVIEW

**Comment by pgdr** [comment]
We must ensure that newly posted values will have `rawdata.s_id != null`, though.

**Comment by pgdr** [comment]
Need to update `RawData.create` with `rd.s_id=sensor`.

**Comment by pgdr** [comment]
This is ready to review, and also, I think, ready to merge, push-deploy and migrate.

**Comment by joakim-hove** [comment]
Very very good - I will review and hopefully merge++ tomorrow.

Has the necessary `drop table xxx` commands been issued on the production DB.

**Comment by pgdr** [comment]
Thanks.  The migration takes about 10 minutes, so we should consider putting heroku in maintenance mode.

The most important part in the review is agreeing with me that I fixed that only place where we actually insert new rows into RawData (I updated the `RawData.create` function).

I have deleted the aforementioned tables in prod.

**Pull request merged**
